Support prefixing key names in keygen script.
Changelog: None

Signed-off-by: Eystein Måløy Stenberg <eystein@mender.io>
(cherry picked from commit d667992ae1b8b63c7b5e39e990e449ae3dcfc2ce)

diff --git a/support/keygen-client b/support/keygen-client
--- a/support/keygen-client
+++ b/support/keygen-client
@@ -1,8 +1,17 @@
 #!/bin/bash
 set -e
 
-FILE_NAME_PRIVATE_KEY="private.key"
-FILE_NAME_PUBLIC_KEY="public.key"
+if [[ $PREFIX_KEY = *"/"* ]]; then
+  echo "ERROR: Environment variable PREFIX_KEY contains path separators: $PREFIX_KEY"
+  echo "Example: PREFIX_KEY=\"0001-\" $0"
+  exit 1
+fi
+
+PRIVATE_KEY="private.key"
+PUBLIC_KEY="public.key"
+
+FILE_NAME_PRIVATE_KEY="$PREFIX_KEY$PRIVATE_KEY"
+FILE_NAME_PUBLIC_KEY="$PREFIX_KEY$PUBLIC_KEY"
 
 # verify openssl is present and sufficiently recent (genpkey seems to require openssl 1.0+)
 command -v openssl >/dev/null 2>&1 || { echo >&2 "ERROR: Please install the openssl utility version 1.0.0 or newer to generate keys."; exit 1; }
