inventory geo script: switch to ipapi.co
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

diff --git a/support/mender-inventory-geo b/support/mender-inventory-geo
--- a/support/mender-inventory-geo
+++ b/support/mender-inventory-geo
@@ -23,6 +23,8 @@
 # but in the following we assume busybox version of the utilities.
 # see below for the configuration of the attributes names
 
+TIMEOUT=10 # 10 seconds timeout to get the information
+
 err() {
  local rc=$1
 
@@ -31,17 +33,10 @@ err() {
  exit $rc
 }
 
-# find the ip address
-ip=`wget -qO /dev/stdout --header "Content-Type: text/plain;" \
-     --header 'Host: ifconfig.io' --header 'User-Agent: curl/7.67.0' \
-     --header 'Accept: */*' ifconfig.io | tail -1`
+# get the geo information
+geo=`wget --timeout=${TIMEOUT} -qO /dev/stdout https://ipapi.co/csv 2>/dev/null | tail -1`
 
-[ -n "${ip}" ] || err 2 "Unable to get the IP address from ifconfig.io"
-
-# get the information, see https://www.ipvigilante.com/api-developer-docs/
-geo=`wget -qO /dev/stdout https://ipvigilante.com/csv/${ip} 2>/dev/null`
-
-[ -n "${geo}" ] || err 3 "Unable to get the geolocalization data from ipvigilante.com"
+[ -n "${geo}" ] || err 3 "Unable to get the geolocalization data from ipapi.co"
 
 # the names of the attributes holding the localization data can be configured here
 ATTR_NAME_IP="geo-ip"
@@ -52,6 +47,6 @@ ATTR_NAME_CITY="geo-city"
 echo "${geo}" | awk -v ip="${ATTR_NAME_IP}" -v continent="${ATTR_NAME_CONTINENT}" \
     -v country="${ATTR_NAME_COUNTRY}" -v city="${ATTR_NAME_CITY}" -F',' \
     ' length($NF) == 0 { exit(4) }
-      { printf("%s=%s\n%s=%s\n%s=%s\n%s=%s\n",ip,$1,continent,$2,country,$3,city,$6) }
+      { printf("%s=%s\n%s=%s\n%s=%s\n%s=%s\n",ip,$16,continent,$3,country,$4,city,$2) }
     '
 
