rootfs-image-v2 hardening: check that root mount matches boot env.
Changelog: None

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

diff --git a/tests/rootfs-image-v2 b/tests/rootfs-image-v2
--- a/tests/rootfs-image-v2
+++ b/tests/rootfs-image-v2
@@ -21,24 +21,35 @@ fi
 active_num="$(${PRINTENV} mender_boot_part)"
 active_num="${active_num#mender_boot_part=}"
 if test $active_num -eq $MENDER_ROOTFS_PART_A_NUMBER; then
+    active=$MENDER_ROOTFS_PART_A
     passive=$MENDER_ROOTFS_PART_B
     passive_num=$MENDER_ROOTFS_PART_B_NUMBER
 else
+    active=$MENDER_ROOTFS_PART_B
     passive=$MENDER_ROOTFS_PART_A
     passive_num=$MENDER_ROOTFS_PART_A_NUMBER
 fi
 
+ensure_correct_root_mounted() {
+    if [ "$(stat -L -c %02t%02T $active)" != "$(stat -L -c %04D /)" ]; then
+        echo "Mounted root does not match boot loader environment!" 1>&2
+        exit 1
+    fi
+}
+
 case "$1" in
     Download)
+        ensure_correct_root_mounted
         file="$(cat stream-next)"
         cat "$file" > $passive
         if [ "$(cat stream-next)" != "" ]; then
-            echo "More than one file in payload"
+            echo "More than one file in payload" 1>&2
             exit 1
         fi
         ;;
 
     ArtifactInstall)
+        ensure_correct_root_mounted
         ${SETENV} -s - <<EOF
 mender_boot_part $passive_num
 upgrade_available 1
@@ -59,29 +70,33 @@ EOF
         ;;
 
     ArtifactVerifyReboot)
+        ensure_correct_root_mounted
         if test "$(${PRINTENV} upgrade_available)" != "upgrade_available=1"; then
             exit 1
         fi
         ;;
 
     ArtifactVerifyRollbackReboot)
+        ensure_correct_root_mounted
         if test "$(${PRINTENV} upgrade_available)" = "upgrade_available=1"; then
             exit 1
         fi
         ;;
 
     ArtifactCommit)
+        ensure_correct_root_mounted
         if test "$(${PRINTENV} upgrade_available)" = "upgrade_available=1"; then
             ${SETENV} upgrade_available 0
         else
             # If we get here, an upgrade in standalone mode failed to boot and the user is trying to commit from the old OS.
             # This communicates to the user that the upgrade failed.
-            echo "Upgrade failed and was reverted: refusing to commit!"
+            echo "Upgrade failed and was reverted: refusing to commit!" 1>&2
             exit 1
         fi
         ;;
 
     ArtifactRollback)
+        ensure_correct_root_mounted
         if test "$(${PRINTENV} upgrade_available)" = "upgrade_available=1"; then
             ${SETENV} -s - <<EOF
 mender_boot_part $passive_num
