feat: changed parsing of some passthrough args in generators
Changelog: Returns an error when passing type, or when passing metadata
to docker-artifact gen, and overrides output path
and name when passed as passthrough argument.

Ticket: MEN-7110

Signed-off-by: Daniel Skinstad Drabitzius <daniel.drabitzius@northern.tech>

diff --git a/support/modules-artifact-gen/directory-artifact-gen b/support/modules-artifact-gen/directory-artifact-gen
--- a/support/modules-artifact-gen/directory-artifact-gen
+++ b/support/modules-artifact-gen/directory-artifact-gen
@@ -161,9 +161,31 @@ else
   exit 1
 fi
 
-
 # Create dest_dir file in plain text
 echo "$dest_dir" > $dest_dir_file
+
+# Check the the passthrough_args and potentially modify them
+# to avoid conflicts or to let them override the already args
+# provided to mender-artifact
+passthrough_args_modified=" "
+parse=$(xargs -n 2 printf "%s %s\n" <<< $passthrough_args)
+while read -r flag arg; do
+  case $flag in
+    -T | --type)
+      echo "Error: Conflicting flag '$flag'. Already specified by the script."
+      exit 1
+      ;;
+    -o | --output-path)
+        output_path=$arg
+      ;;
+    -n | --name)
+        artifact_name=$arg
+      ;;
+    *)
+      passthrough_args_modified+="$flag $arg "
+      ;;
+  esac
+done <<< $parse
 
 mender-artifact write module-image \
   -T directory \
@@ -172,7 +194,7 @@ mender-artifact write module-image \
   -n $artifact_name \
   -f $update_files_tar \
   -f $dest_dir_file \
-  $passthrough_args
+  $passthrough_args_modified
 
 rm $update_files_tar
 rm $dest_dir_file
diff --git a/support/modules-artifact-gen/single-file-artifact-gen b/support/modules-artifact-gen/single-file-artifact-gen
--- a/support/modules-artifact-gen/single-file-artifact-gen
+++ b/support/modules-artifact-gen/single-file-artifact-gen
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 set -e
 
@@ -178,6 +178,30 @@ else
   stat -c %a "${file}" > $permissions_file
 fi
 
+# Check the the passthrough_args and potentially modify them
+# to avoid conflicts or to let them override the already args
+# provided to mender-artifact
+passthrough_args_modified=" "
+parse=$(xargs -n 2 printf "%s %s\n" <<< $passthrough_args)
+while read -r flag arg; do
+  case $flag in
+    -T | --type)
+      echo "Error: Conflicting flag '$flag'. Already specified by the script."
+      exit 1
+      ;;
+    -o | --output-path)
+        output_path=$arg
+      ;;
+    -n | --name)
+        artifact_name=$arg
+      ;;
+    *)
+      passthrough_args_modified+="$flag $arg "
+      ;;
+  esac
+done <<< $parse
+echo passthrough_args_modified: $passthrough_args_modified
+
 mender-artifact write module-image \
   -T single-file \
   $device_types \
@@ -187,7 +211,7 @@ mender-artifact write module-image \
   -f "$filename_file" \
   -f "$permissions_file" \
   -f "$file" \
-  $passthrough_args
+  $passthrough_args_modified
 
 rm -rf $tmpdir
 
