Disallow installing file trees in root dest dir
The update module still supports single file install in /

Improve also other error missages

Changelog: Disallow installing file trees on root destination dir for
File Install Update Module

Signed-off-by: Lluis Campos <lluis.campos@northern.tech>

diff --git a/support/modules-artifact-gen/file-install-artifact-gen b/support/modules-artifact-gen/file-install-artifact-gen
--- a/support/modules-artifact-gen/file-install-artifact-gen
+++ b/support/modules-artifact-gen/file-install-artifact-gen
@@ -124,6 +124,10 @@ esac
 single_file=""
 if [ -e "${file_tree}" ]; then
   if [ -d "${file_tree}" ]; then
+    if [ "$dest_dir" == "/" ]; then
+      echo "Error: this Update Module does not support file tree deployment at /"
+      exit 1
+    fi
     tar -cf ${update_files_tar} -C "${file_tree}" .
     single_file="false"
   elif [ -f "${file_tree}" ]; then
diff --git a/support/modules/file-install b/support/modules/file-install
--- a/support/modules/file-install
+++ b/support/modules/file-install
@@ -24,13 +24,16 @@ case "$STATE" in
     ArtifactInstall)
         dest_dir=$(cat $dest_dir_file)
         single_file=$(cat $single_file_file)
-        test -z "$dest_dir" -o -z "$single_file" && exit 1
+        test -z "$dest_dir" -o -z "$single_file" && \
+        echo "Fatal error: dest_dir or single_file are undefined." && exit 1
         mkdir -p $dest_dir
         if [ $single_file == "true" ]; then
             mkdir -p $tmp_dest_dir
             filename=$(tar -tf ${update_files_tar})
             [[ -f ${dest_dir}/${filename} ]] && tar -cf ${prev_files_tar} -C ${dest_dir} ${filename}
         else
+            test "$dest_dir" == "/" && \
+            echo "Error: destination dir is '/', install not supported." && exit 1
             tar -cf ${prev_files_tar} -C ${dest_dir} .
             rm -rf ${dest_dir}
             mkdir -p ${dest_dir}
@@ -41,11 +44,14 @@ case "$STATE" in
     ArtifactRollback)
         dest_dir=$(cat $dest_dir_file)
         single_file=$(cat $single_file_file)
-        test -z "$dest_dir" -o -z "$single_file" && exit 1
+        test -z "$dest_dir" -o -z "$single_file" && \
+        echo "Fatal error: dest_dir or single_file are undefined." && exit 1
         if [ $single_file == "true" ]; then
             filename=$(tar -tf ${update_files_tar})
             rm ${dest_dir}/${filename}
         else
+            test "$dest_dir" == "/" && \
+            echo "Info: destination dir is '/', not performing rollback." && exit 0
             rm -rf ${dest_dir}
             mkdir -p ${dest_dir}
         fi
