single-file: Use stderr for all error messages.
Changelog: Title

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
(cherry picked from commit 1aeae01ab1b408b7e9bbb27d8f2547437a9243e4)

diff --git a/support/modules/single-file b/support/modules/single-file
--- a/support/modules/single-file
+++ b/support/modules/single-file
@@ -35,7 +35,7 @@ case "$STATE" in
         dest_dir=$(cat "${dest_dir_file}")
         filename=$(cat "${filename_file}")
         test -z "$dest_dir" -o -z "$filename" && \
-            echo "Fatal error: dest_dir or filename are undefined." && exit 1
+            echo "Fatal error: dest_dir or filename are undefined." >&2 && exit 1
         mkdir -p "${dest_dir}"
         mkdir -p "${tmp_dest_dir}"
         if test -f "${dest_dir}/${filename}"
